/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/discovery.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf/discovery.pb-c.h"
void   cmsg_remote_client_broadcast_header__init
                     (CMsgRemoteClientBroadcastHeader         *message)
{
  static const CMsgRemoteClientBroadcastHeader init_value = CMSG_REMOTE_CLIENT_BROADCAST_HEADER__INIT;
  *message = init_value;
}
size_t cmsg_remote_client_broadcast_header__get_packed_size
                     (const CMsgRemoteClientBroadcastHeader *message)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_client_broadcast_header__pack
                     (const CMsgRemoteClientBroadcastHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_client_broadcast_header__pack_to_buffer
                     (const CMsgRemoteClientBroadcastHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteClientBroadcastHeader *
       cmsg_remote_client_broadcast_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteClientBroadcastHeader *)
     protobuf_c_message_unpack (&cmsg_remote_client_broadcast_header__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_client_broadcast_header__free_unpacked
                     (CMsgRemoteClientBroadcastHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_client_broadcast_status__user__init
                     (CMsgRemoteClientBroadcastStatus__User         *message)
{
  static const CMsgRemoteClientBroadcastStatus__User init_value = CMSG_REMOTE_CLIENT_BROADCAST_STATUS__USER__INIT;
  *message = init_value;
}
void   cmsg_remote_client_broadcast_status__init
                     (CMsgRemoteClientBroadcastStatus         *message)
{
  static const CMsgRemoteClientBroadcastStatus init_value = CMSG_REMOTE_CLIENT_BROADCAST_STATUS__INIT;
  *message = init_value;
}
size_t cmsg_remote_client_broadcast_status__get_packed_size
                     (const CMsgRemoteClientBroadcastStatus *message)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_client_broadcast_status__pack
                     (const CMsgRemoteClientBroadcastStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_client_broadcast_status__pack_to_buffer
                     (const CMsgRemoteClientBroadcastStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteClientBroadcastStatus *
       cmsg_remote_client_broadcast_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteClientBroadcastStatus *)
     protobuf_c_message_unpack (&cmsg_remote_client_broadcast_status__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_client_broadcast_status__free_unpacked
                     (CMsgRemoteClientBroadcastStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_client_broadcast_discovery__init
                     (CMsgRemoteClientBroadcastDiscovery         *message)
{
  static const CMsgRemoteClientBroadcastDiscovery init_value = CMSG_REMOTE_CLIENT_BROADCAST_DISCOVERY__INIT;
  *message = init_value;
}
size_t cmsg_remote_client_broadcast_discovery__get_packed_size
                     (const CMsgRemoteClientBroadcastDiscovery *message)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_discovery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_client_broadcast_discovery__pack
                     (const CMsgRemoteClientBroadcastDiscovery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_discovery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_client_broadcast_discovery__pack_to_buffer
                     (const CMsgRemoteClientBroadcastDiscovery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_discovery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteClientBroadcastDiscovery *
       cmsg_remote_client_broadcast_discovery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteClientBroadcastDiscovery *)
     protobuf_c_message_unpack (&cmsg_remote_client_broadcast_discovery__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_client_broadcast_discovery__free_unpacked
                     (CMsgRemoteClientBroadcastDiscovery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_discovery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_client_broadcast_client_iddeconflict__init
                     (CMsgRemoteClientBroadcastClientIDDeconflict         *message)
{
  static const CMsgRemoteClientBroadcastClientIDDeconflict init_value = CMSG_REMOTE_CLIENT_BROADCAST_CLIENT_IDDECONFLICT__INIT;
  *message = init_value;
}
size_t cmsg_remote_client_broadcast_client_iddeconflict__get_packed_size
                     (const CMsgRemoteClientBroadcastClientIDDeconflict *message)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_client_iddeconflict__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_client_broadcast_client_iddeconflict__pack
                     (const CMsgRemoteClientBroadcastClientIDDeconflict *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_client_iddeconflict__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_client_broadcast_client_iddeconflict__pack_to_buffer
                     (const CMsgRemoteClientBroadcastClientIDDeconflict *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_client_iddeconflict__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteClientBroadcastClientIDDeconflict *
       cmsg_remote_client_broadcast_client_iddeconflict__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteClientBroadcastClientIDDeconflict *)
     protobuf_c_message_unpack (&cmsg_remote_client_broadcast_client_iddeconflict__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_client_broadcast_client_iddeconflict__free_unpacked
                     (CMsgRemoteClientBroadcastClientIDDeconflict *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_client_broadcast_client_iddeconflict__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_authorization_request__ckey_escrow__ticket__init
                     (CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket         *message)
{
  static const CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket init_value = CMSG_REMOTE_DEVICE_AUTHORIZATION_REQUEST__CKEY_ESCROW__TICKET__INIT;
  *message = init_value;
}
void   cmsg_remote_device_authorization_request__init
                     (CMsgRemoteDeviceAuthorizationRequest         *message)
{
  static const CMsgRemoteDeviceAuthorizationRequest init_value = CMSG_REMOTE_DEVICE_AUTHORIZATION_REQUEST__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_authorization_request__get_packed_size
                     (const CMsgRemoteDeviceAuthorizationRequest *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_authorization_request__pack
                     (const CMsgRemoteDeviceAuthorizationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_authorization_request__pack_to_buffer
                     (const CMsgRemoteDeviceAuthorizationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceAuthorizationRequest *
       cmsg_remote_device_authorization_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceAuthorizationRequest *)
     protobuf_c_message_unpack (&cmsg_remote_device_authorization_request__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_authorization_request__free_unpacked
                     (CMsgRemoteDeviceAuthorizationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_authorization_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_authorization_cancel_request__init
                     (CMsgRemoteDeviceAuthorizationCancelRequest         *message)
{
  static const CMsgRemoteDeviceAuthorizationCancelRequest init_value = CMSG_REMOTE_DEVICE_AUTHORIZATION_CANCEL_REQUEST__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_authorization_cancel_request__get_packed_size
                     (const CMsgRemoteDeviceAuthorizationCancelRequest *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_cancel_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_authorization_cancel_request__pack
                     (const CMsgRemoteDeviceAuthorizationCancelRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_cancel_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_authorization_cancel_request__pack_to_buffer
                     (const CMsgRemoteDeviceAuthorizationCancelRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_cancel_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceAuthorizationCancelRequest *
       cmsg_remote_device_authorization_cancel_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceAuthorizationCancelRequest *)
     protobuf_c_message_unpack (&cmsg_remote_device_authorization_cancel_request__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_authorization_cancel_request__free_unpacked
                     (CMsgRemoteDeviceAuthorizationCancelRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_authorization_cancel_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_authorization_response__init
                     (CMsgRemoteDeviceAuthorizationResponse         *message)
{
  static const CMsgRemoteDeviceAuthorizationResponse init_value = CMSG_REMOTE_DEVICE_AUTHORIZATION_RESPONSE__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_authorization_response__get_packed_size
                     (const CMsgRemoteDeviceAuthorizationResponse *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_authorization_response__pack
                     (const CMsgRemoteDeviceAuthorizationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_authorization_response__pack_to_buffer
                     (const CMsgRemoteDeviceAuthorizationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_authorization_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceAuthorizationResponse *
       cmsg_remote_device_authorization_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceAuthorizationResponse *)
     protobuf_c_message_unpack (&cmsg_remote_device_authorization_response__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_authorization_response__free_unpacked
                     (CMsgRemoteDeviceAuthorizationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_authorization_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_streaming_request__reserved_gamepad__init
                     (CMsgRemoteDeviceStreamingRequest__ReservedGamepad         *message)
{
  static const CMsgRemoteDeviceStreamingRequest__ReservedGamepad init_value = CMSG_REMOTE_DEVICE_STREAMING_REQUEST__RESERVED_GAMEPAD__INIT;
  *message = init_value;
}
void   cmsg_remote_device_streaming_request__init
                     (CMsgRemoteDeviceStreamingRequest         *message)
{
  static const CMsgRemoteDeviceStreamingRequest init_value = CMSG_REMOTE_DEVICE_STREAMING_REQUEST__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_streaming_request__get_packed_size
                     (const CMsgRemoteDeviceStreamingRequest *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_streaming_request__pack
                     (const CMsgRemoteDeviceStreamingRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_streaming_request__pack_to_buffer
                     (const CMsgRemoteDeviceStreamingRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceStreamingRequest *
       cmsg_remote_device_streaming_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceStreamingRequest *)
     protobuf_c_message_unpack (&cmsg_remote_device_streaming_request__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_streaming_request__free_unpacked
                     (CMsgRemoteDeviceStreamingRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_streaming_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_streaming_cancel_request__init
                     (CMsgRemoteDeviceStreamingCancelRequest         *message)
{
  static const CMsgRemoteDeviceStreamingCancelRequest init_value = CMSG_REMOTE_DEVICE_STREAMING_CANCEL_REQUEST__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_streaming_cancel_request__get_packed_size
                     (const CMsgRemoteDeviceStreamingCancelRequest *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_cancel_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_streaming_cancel_request__pack
                     (const CMsgRemoteDeviceStreamingCancelRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_cancel_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_streaming_cancel_request__pack_to_buffer
                     (const CMsgRemoteDeviceStreamingCancelRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_cancel_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceStreamingCancelRequest *
       cmsg_remote_device_streaming_cancel_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceStreamingCancelRequest *)
     protobuf_c_message_unpack (&cmsg_remote_device_streaming_cancel_request__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_streaming_cancel_request__free_unpacked
                     (CMsgRemoteDeviceStreamingCancelRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_streaming_cancel_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_streaming_progress__init
                     (CMsgRemoteDeviceStreamingProgress         *message)
{
  static const CMsgRemoteDeviceStreamingProgress init_value = CMSG_REMOTE_DEVICE_STREAMING_PROGRESS__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_streaming_progress__get_packed_size
                     (const CMsgRemoteDeviceStreamingProgress *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_progress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_streaming_progress__pack
                     (const CMsgRemoteDeviceStreamingProgress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_progress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_streaming_progress__pack_to_buffer
                     (const CMsgRemoteDeviceStreamingProgress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_progress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceStreamingProgress *
       cmsg_remote_device_streaming_progress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceStreamingProgress *)
     protobuf_c_message_unpack (&cmsg_remote_device_streaming_progress__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_streaming_progress__free_unpacked
                     (CMsgRemoteDeviceStreamingProgress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_streaming_progress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_streaming_response__init
                     (CMsgRemoteDeviceStreamingResponse         *message)
{
  static const CMsgRemoteDeviceStreamingResponse init_value = CMSG_REMOTE_DEVICE_STREAMING_RESPONSE__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_streaming_response__get_packed_size
                     (const CMsgRemoteDeviceStreamingResponse *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_streaming_response__pack
                     (const CMsgRemoteDeviceStreamingResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_streaming_response__pack_to_buffer
                     (const CMsgRemoteDeviceStreamingResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_streaming_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceStreamingResponse *
       cmsg_remote_device_streaming_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceStreamingResponse *)
     protobuf_c_message_unpack (&cmsg_remote_device_streaming_response__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_streaming_response__free_unpacked
                     (CMsgRemoteDeviceStreamingResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_streaming_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_proof_request__init
                     (CMsgRemoteDeviceProofRequest         *message)
{
  static const CMsgRemoteDeviceProofRequest init_value = CMSG_REMOTE_DEVICE_PROOF_REQUEST__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_proof_request__get_packed_size
                     (const CMsgRemoteDeviceProofRequest *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_proof_request__pack
                     (const CMsgRemoteDeviceProofRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_proof_request__pack_to_buffer
                     (const CMsgRemoteDeviceProofRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceProofRequest *
       cmsg_remote_device_proof_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceProofRequest *)
     protobuf_c_message_unpack (&cmsg_remote_device_proof_request__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_proof_request__free_unpacked
                     (CMsgRemoteDeviceProofRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_proof_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_proof_response__init
                     (CMsgRemoteDeviceProofResponse         *message)
{
  static const CMsgRemoteDeviceProofResponse init_value = CMSG_REMOTE_DEVICE_PROOF_RESPONSE__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_proof_response__get_packed_size
                     (const CMsgRemoteDeviceProofResponse *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_proof_response__pack
                     (const CMsgRemoteDeviceProofResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_proof_response__pack_to_buffer
                     (const CMsgRemoteDeviceProofResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_proof_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceProofResponse *
       cmsg_remote_device_proof_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceProofResponse *)
     protobuf_c_message_unpack (&cmsg_remote_device_proof_response__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_proof_response__free_unpacked
                     (CMsgRemoteDeviceProofResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_proof_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_remote_device_stream_transport_signal__init
                     (CMsgRemoteDeviceStreamTransportSignal         *message)
{
  static const CMsgRemoteDeviceStreamTransportSignal init_value = CMSG_REMOTE_DEVICE_STREAM_TRANSPORT_SIGNAL__INIT;
  *message = init_value;
}
size_t cmsg_remote_device_stream_transport_signal__get_packed_size
                     (const CMsgRemoteDeviceStreamTransportSignal *message)
{
  assert(message->base.descriptor == &cmsg_remote_device_stream_transport_signal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_remote_device_stream_transport_signal__pack
                     (const CMsgRemoteDeviceStreamTransportSignal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmsg_remote_device_stream_transport_signal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_remote_device_stream_transport_signal__pack_to_buffer
                     (const CMsgRemoteDeviceStreamTransportSignal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmsg_remote_device_stream_transport_signal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CMsgRemoteDeviceStreamTransportSignal *
       cmsg_remote_device_stream_transport_signal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CMsgRemoteDeviceStreamTransportSignal *)
     protobuf_c_message_unpack (&cmsg_remote_device_stream_transport_signal__descriptor,
                                allocator, len, data);
}
void   cmsg_remote_device_stream_transport_signal__free_unpacked
                     (CMsgRemoteDeviceStreamTransportSignal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmsg_remote_device_stream_transport_signal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cmsg_remote_client_broadcast_header__field_descriptors[5] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteClientBroadcastHeader, has_client_id),
    offsetof(CMsgRemoteClientBroadcastHeader, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteClientBroadcastHeader, has_msg_type),
    offsetof(CMsgRemoteClientBroadcastHeader, msg_type),
    &eremote_client_broadcast_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteClientBroadcastHeader, has_instance_id),
    offsetof(CMsgRemoteClientBroadcastHeader, instance_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteClientBroadcastHeader, has_device_id),
    offsetof(CMsgRemoteClientBroadcastHeader, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_token",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteClientBroadcastHeader, has_device_token),
    offsetof(CMsgRemoteClientBroadcastHeader, device_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_client_broadcast_header__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  3,   /* field[3] = device_id */
  4,   /* field[4] = device_token */
  2,   /* field[2] = instance_id */
  1,   /* field[1] = msg_type */
};
static const ProtobufCIntRange cmsg_remote_client_broadcast_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cmsg_remote_client_broadcast_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteClientBroadcastHeader",
  "CMsgRemoteClientBroadcastHeader",
  "CMsgRemoteClientBroadcastHeader",
  "",
  sizeof(CMsgRemoteClientBroadcastHeader),
  5,
  cmsg_remote_client_broadcast_header__field_descriptors,
  cmsg_remote_client_broadcast_header__field_indices_by_name,
  1,  cmsg_remote_client_broadcast_header__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_client_broadcast_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_client_broadcast_status__user__field_descriptors[2] =
{
  {
    "steamid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CMsgRemoteClientBroadcastStatus__User, has_steamid),
    offsetof(CMsgRemoteClientBroadcastStatus__User, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_key_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus__User, has_auth_key_id),
    offsetof(CMsgRemoteClientBroadcastStatus__User, auth_key_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_client_broadcast_status__user__field_indices_by_name[] = {
  1,   /* field[1] = auth_key_id */
  0,   /* field[0] = steamid */
};
static const ProtobufCIntRange cmsg_remote_client_broadcast_status__user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_client_broadcast_status__user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteClientBroadcastStatus.User",
  "User",
  "CMsgRemoteClientBroadcastStatus__User",
  "",
  sizeof(CMsgRemoteClientBroadcastStatus__User),
  2,
  cmsg_remote_client_broadcast_status__user__field_descriptors,
  cmsg_remote_client_broadcast_status__user__field_indices_by_name,
  1,  cmsg_remote_client_broadcast_status__user__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_client_broadcast_status__user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t cmsg_remote_client_broadcast_status__ostype__default_value = 0;
static const ProtobufCFieldDescriptor cmsg_remote_client_broadcast_status__field_descriptors[21] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_version),
    offsetof(CMsgRemoteClientBroadcastStatus, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_min_version),
    offsetof(CMsgRemoteClientBroadcastStatus, min_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connect_port",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_connect_port),
    offsetof(CMsgRemoteClientBroadcastStatus, connect_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteClientBroadcastStatus, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled_services",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_enabled_services),
    offsetof(CMsgRemoteClientBroadcastStatus, enabled_services),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ostype",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_ostype),
    offsetof(CMsgRemoteClientBroadcastStatus, ostype),
    NULL,
    &cmsg_remote_client_broadcast_status__ostype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is64bit",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_is64bit),
    offsetof(CMsgRemoteClientBroadcastStatus, is64bit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "users",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgRemoteClientBroadcastStatus, n_users),
    offsetof(CMsgRemoteClientBroadcastStatus, users),
    &cmsg_remote_client_broadcast_status__user__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "euniverse",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_euniverse),
    offsetof(CMsgRemoteClientBroadcastStatus, euniverse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_timestamp),
    offsetof(CMsgRemoteClientBroadcastStatus, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_locked",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_screen_locked),
    offsetof(CMsgRemoteClientBroadcastStatus, screen_locked),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "games_running",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_games_running),
    offsetof(CMsgRemoteClientBroadcastStatus, games_running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_addresses",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(CMsgRemoteClientBroadcastStatus, n_mac_addresses),
    offsetof(CMsgRemoteClientBroadcastStatus, mac_addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "download_lan_peer_group",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_download_lan_peer_group),
    offsetof(CMsgRemoteClientBroadcastStatus, download_lan_peer_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcasting_active",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_broadcasting_active),
    offsetof(CMsgRemoteClientBroadcastStatus, broadcasting_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vr_active",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_vr_active),
    offsetof(CMsgRemoteClientBroadcastStatus, vr_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_cache_port",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_content_cache_port),
    offsetof(CMsgRemoteClientBroadcastStatus, content_cache_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_addresses",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(CMsgRemoteClientBroadcastStatus, n_ip_addresses),
    offsetof(CMsgRemoteClientBroadcastStatus, ip_addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_ip_address",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteClientBroadcastStatus, public_ip_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteplay_active",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteClientBroadcastStatus, has_remoteplay_active),
    offsetof(CMsgRemoteClientBroadcastStatus, remoteplay_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_services",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastStatus, has_supported_services),
    offsetof(CMsgRemoteClientBroadcastStatus, supported_services),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_client_broadcast_status__field_indices_by_name[] = {
  14,   /* field[14] = broadcasting_active */
  2,   /* field[2] = connect_port */
  16,   /* field[16] = content_cache_port */
  13,   /* field[13] = download_lan_peer_group */
  4,   /* field[4] = enabled_services */
  8,   /* field[8] = euniverse */
  11,   /* field[11] = games_running */
  3,   /* field[3] = hostname */
  17,   /* field[17] = ip_addresses */
  6,   /* field[6] = is64bit */
  12,   /* field[12] = mac_addresses */
  1,   /* field[1] = min_version */
  5,   /* field[5] = ostype */
  18,   /* field[18] = public_ip_address */
  19,   /* field[19] = remoteplay_active */
  10,   /* field[10] = screen_locked */
  20,   /* field[20] = supported_services */
  9,   /* field[9] = timestamp */
  7,   /* field[7] = users */
  0,   /* field[0] = version */
  15,   /* field[15] = vr_active */
};
static const ProtobufCIntRange cmsg_remote_client_broadcast_status__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 11, 8 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor cmsg_remote_client_broadcast_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteClientBroadcastStatus",
  "CMsgRemoteClientBroadcastStatus",
  "CMsgRemoteClientBroadcastStatus",
  "",
  sizeof(CMsgRemoteClientBroadcastStatus),
  21,
  cmsg_remote_client_broadcast_status__field_descriptors,
  cmsg_remote_client_broadcast_status__field_indices_by_name,
  3,  cmsg_remote_client_broadcast_status__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_client_broadcast_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_client_broadcast_discovery__field_descriptors[2] =
{
  {
    "seq_num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteClientBroadcastDiscovery, has_seq_num),
    offsetof(CMsgRemoteClientBroadcastDiscovery, seq_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_ids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteClientBroadcastDiscovery, n_client_ids),
    offsetof(CMsgRemoteClientBroadcastDiscovery, client_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_client_broadcast_discovery__field_indices_by_name[] = {
  1,   /* field[1] = client_ids */
  0,   /* field[0] = seq_num */
};
static const ProtobufCIntRange cmsg_remote_client_broadcast_discovery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_client_broadcast_discovery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteClientBroadcastDiscovery",
  "CMsgRemoteClientBroadcastDiscovery",
  "CMsgRemoteClientBroadcastDiscovery",
  "",
  sizeof(CMsgRemoteClientBroadcastDiscovery),
  2,
  cmsg_remote_client_broadcast_discovery__field_descriptors,
  cmsg_remote_client_broadcast_discovery__field_indices_by_name,
  1,  cmsg_remote_client_broadcast_discovery__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_client_broadcast_discovery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_client_broadcast_client_iddeconflict__field_descriptors[1] =
{
  {
    "client_ids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteClientBroadcastClientIDDeconflict, n_client_ids),
    offsetof(CMsgRemoteClientBroadcastClientIDDeconflict, client_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_client_broadcast_client_iddeconflict__field_indices_by_name[] = {
  0,   /* field[0] = client_ids */
};
static const ProtobufCIntRange cmsg_remote_client_broadcast_client_iddeconflict__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cmsg_remote_client_broadcast_client_iddeconflict__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteClientBroadcastClientIDDeconflict",
  "CMsgRemoteClientBroadcastClientIDDeconflict",
  "CMsgRemoteClientBroadcastClientIDDeconflict",
  "",
  sizeof(CMsgRemoteClientBroadcastClientIDDeconflict),
  1,
  cmsg_remote_client_broadcast_client_iddeconflict__field_descriptors,
  cmsg_remote_client_broadcast_client_iddeconflict__field_indices_by_name,
  1,  cmsg_remote_client_broadcast_client_iddeconflict__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_client_broadcast_client_iddeconflict__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_authorization_request__ckey_escrow__ticket__field_descriptors[9] =
{
  {
    "password",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_password),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identifier",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_identifier),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_payload),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_timestamp),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usage",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_usage),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, usage),
    &cmsg_remote_device_authorization_request__ekey_escrow_usage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, device_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_model",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, device_model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_serial",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, device_serial),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_provisioning_id",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, has_device_provisioning_id),
    offsetof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket, device_provisioning_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_authorization_request__ckey_escrow__ticket__field_indices_by_name[] = {
  6,   /* field[6] = device_model */
  5,   /* field[5] = device_name */
  8,   /* field[8] = device_provisioning_id */
  7,   /* field[7] = device_serial */
  1,   /* field[1] = identifier */
  0,   /* field[0] = password */
  2,   /* field[2] = payload */
  3,   /* field[3] = timestamp */
  4,   /* field[4] = usage */
};
static const ProtobufCIntRange cmsg_remote_device_authorization_request__ckey_escrow__ticket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_authorization_request__ckey_escrow__ticket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceAuthorizationRequest.CKeyEscrow_Ticket",
  "CKeyEscrowTicket",
  "CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket",
  "",
  sizeof(CMsgRemoteDeviceAuthorizationRequest__CKeyEscrowTicket),
  9,
  cmsg_remote_device_authorization_request__ckey_escrow__ticket__field_descriptors,
  cmsg_remote_device_authorization_request__ckey_escrow__ticket__field_indices_by_name,
  1,  cmsg_remote_device_authorization_request__ckey_escrow__ticket__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_authorization_request__ckey_escrow__ticket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cmsg_remote_device_authorization_request__ekey_escrow_usage__enum_values_by_number[1] =
{
  { "k_EKeyEscrowUsageStreamingDevice", "k_EKeyEscrowUsageStreamingDevice", 0 },
};
static const ProtobufCIntRange cmsg_remote_device_authorization_request__ekey_escrow_usage__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex cmsg_remote_device_authorization_request__ekey_escrow_usage__enum_values_by_name[1] =
{
  { "k_EKeyEscrowUsageStreamingDevice", 0 },
};
const ProtobufCEnumDescriptor cmsg_remote_device_authorization_request__ekey_escrow_usage__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage",
  "EKeyEscrowUsage",
  "CMsgRemoteDeviceAuthorizationRequest__EKeyEscrowUsage",
  "",
  1,
  cmsg_remote_device_authorization_request__ekey_escrow_usage__enum_values_by_number,
  1,
  cmsg_remote_device_authorization_request__ekey_escrow_usage__enum_values_by_name,
  1,
  cmsg_remote_device_authorization_request__ekey_escrow_usage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_authorization_request__field_descriptors[3] =
{
  {
    "device_token",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest, device_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest, device_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_request",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationRequest, encrypted_request),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_authorization_request__field_indices_by_name[] = {
  1,   /* field[1] = device_name */
  0,   /* field[0] = device_token */
  2,   /* field[2] = encrypted_request */
};
static const ProtobufCIntRange cmsg_remote_device_authorization_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_authorization_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceAuthorizationRequest",
  "CMsgRemoteDeviceAuthorizationRequest",
  "CMsgRemoteDeviceAuthorizationRequest",
  "",
  sizeof(CMsgRemoteDeviceAuthorizationRequest),
  3,
  cmsg_remote_device_authorization_request__field_descriptors,
  cmsg_remote_device_authorization_request__field_indices_by_name,
  1,  cmsg_remote_device_authorization_request__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_authorization_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cmsg_remote_device_authorization_cancel_request__field_descriptors NULL
#define cmsg_remote_device_authorization_cancel_request__field_indices_by_name NULL
#define cmsg_remote_device_authorization_cancel_request__number_ranges NULL
const ProtobufCMessageDescriptor cmsg_remote_device_authorization_cancel_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceAuthorizationCancelRequest",
  "CMsgRemoteDeviceAuthorizationCancelRequest",
  "CMsgRemoteDeviceAuthorizationCancelRequest",
  "",
  sizeof(CMsgRemoteDeviceAuthorizationCancelRequest),
  0,
  cmsg_remote_device_authorization_cancel_request__field_descriptors,
  cmsg_remote_device_authorization_cancel_request__field_indices_by_name,
  0,  cmsg_remote_device_authorization_cancel_request__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_authorization_cancel_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_authorization_response__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceAuthorizationResponse, result),
    &eremote_device_authorization_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steamid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(CMsgRemoteDeviceAuthorizationResponse, has_steamid),
    offsetof(CMsgRemoteDeviceAuthorizationResponse, steamid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_authorization_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = steamid */
};
static const ProtobufCIntRange cmsg_remote_device_authorization_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_authorization_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceAuthorizationResponse",
  "CMsgRemoteDeviceAuthorizationResponse",
  "CMsgRemoteDeviceAuthorizationResponse",
  "",
  sizeof(CMsgRemoteDeviceAuthorizationResponse),
  2,
  cmsg_remote_device_authorization_response__field_descriptors,
  cmsg_remote_device_authorization_response__field_indices_by_name,
  1,  cmsg_remote_device_authorization_response__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_authorization_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_streaming_request__reserved_gamepad__field_descriptors[2] =
{
  {
    "controller_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceStreamingRequest__ReservedGamepad, has_controller_type),
    offsetof(CMsgRemoteDeviceStreamingRequest__ReservedGamepad, controller_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "controller_subtype",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceStreamingRequest__ReservedGamepad, has_controller_subtype),
    offsetof(CMsgRemoteDeviceStreamingRequest__ReservedGamepad, controller_subtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_streaming_request__reserved_gamepad__field_indices_by_name[] = {
  1,   /* field[1] = controller_subtype */
  0,   /* field[0] = controller_type */
};
static const ProtobufCIntRange cmsg_remote_device_streaming_request__reserved_gamepad__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_streaming_request__reserved_gamepad__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamingRequest.ReservedGamepad",
  "ReservedGamepad",
  "CMsgRemoteDeviceStreamingRequest__ReservedGamepad",
  "",
  sizeof(CMsgRemoteDeviceStreamingRequest__ReservedGamepad),
  2,
  cmsg_remote_device_streaming_request__reserved_gamepad__field_descriptors,
  cmsg_remote_device_streaming_request__reserved_gamepad__field_indices_by_name,
  1,  cmsg_remote_device_streaming_request__reserved_gamepad__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_streaming_request__reserved_gamepad__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t cmsg_remote_device_streaming_request__audio_channel_count__default_value = 2;
static const protobuf_c_boolean cmsg_remote_device_streaming_request__enable_video_streaming__default_value = 1;
static const protobuf_c_boolean cmsg_remote_device_streaming_request__enable_audio_streaming__default_value = 1;
static const protobuf_c_boolean cmsg_remote_device_streaming_request__enable_input_streaming__default_value = 1;
static const ProtobufCFieldDescriptor cmsg_remote_device_streaming_request__field_descriptors[20] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingRequest, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum_resolution_x",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_maximum_resolution_x),
    offsetof(CMsgRemoteDeviceStreamingRequest, maximum_resolution_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum_resolution_y",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_maximum_resolution_y),
    offsetof(CMsgRemoteDeviceStreamingRequest, maximum_resolution_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_channel_count",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_audio_channel_count),
    offsetof(CMsgRemoteDeviceStreamingRequest, audio_channel_count),
    NULL,
    &cmsg_remote_device_streaming_request__audio_channel_count__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_version",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingRequest, device_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_desktop",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_stream_desktop),
    offsetof(CMsgRemoteDeviceStreamingRequest, stream_desktop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_token",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_device_token),
    offsetof(CMsgRemoteDeviceStreamingRequest, device_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pin",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_pin),
    offsetof(CMsgRemoteDeviceStreamingRequest, pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_video_streaming",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_enable_video_streaming),
    offsetof(CMsgRemoteDeviceStreamingRequest, enable_video_streaming),
    NULL,
    &cmsg_remote_device_streaming_request__enable_video_streaming__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_audio_streaming",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_enable_audio_streaming),
    offsetof(CMsgRemoteDeviceStreamingRequest, enable_audio_streaming),
    NULL,
    &cmsg_remote_device_streaming_request__enable_audio_streaming__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_input_streaming",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_enable_input_streaming),
    offsetof(CMsgRemoteDeviceStreamingRequest, enable_input_streaming),
    NULL,
    &cmsg_remote_device_streaming_request__enable_input_streaming__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_test",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_network_test),
    offsetof(CMsgRemoteDeviceStreamingRequest, network_test),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_client_id),
    offsetof(CMsgRemoteDeviceStreamingRequest, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_transport",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteDeviceStreamingRequest, n_supported_transport),
    offsetof(CMsgRemoteDeviceStreamingRequest, supported_transport),
    &estream_transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restricted",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_restricted),
    offsetof(CMsgRemoteDeviceStreamingRequest, restricted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "form_factor",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_form_factor),
    offsetof(CMsgRemoteDeviceStreamingRequest, form_factor),
    &estream_device_form_factor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gamepad_count",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_gamepad_count),
    offsetof(CMsgRemoteDeviceStreamingRequest, gamepad_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gamepads",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CMsgRemoteDeviceStreamingRequest, n_gamepads),
    offsetof(CMsgRemoteDeviceStreamingRequest, gamepads),
    &cmsg_remote_device_streaming_request__reserved_gamepad__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gameid",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_gameid),
    offsetof(CMsgRemoteDeviceStreamingRequest, gameid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_interface",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteDeviceStreamingRequest, has_stream_interface),
    offsetof(CMsgRemoteDeviceStreamingRequest, stream_interface),
    &estream_interface__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_streaming_request__field_indices_by_name[] = {
  3,   /* field[3] = audio_channel_count */
  12,   /* field[12] = client_id */
  6,   /* field[6] = device_token */
  4,   /* field[4] = device_version */
  9,   /* field[9] = enable_audio_streaming */
  10,   /* field[10] = enable_input_streaming */
  8,   /* field[8] = enable_video_streaming */
  15,   /* field[15] = form_factor */
  18,   /* field[18] = gameid */
  16,   /* field[16] = gamepad_count */
  17,   /* field[17] = gamepads */
  1,   /* field[1] = maximum_resolution_x */
  2,   /* field[2] = maximum_resolution_y */
  11,   /* field[11] = network_test */
  7,   /* field[7] = pin */
  0,   /* field[0] = request_id */
  14,   /* field[14] = restricted */
  5,   /* field[5] = stream_desktop */
  19,   /* field[19] = stream_interface */
  13,   /* field[13] = supported_transport */
};
static const ProtobufCIntRange cmsg_remote_device_streaming_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_streaming_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamingRequest",
  "CMsgRemoteDeviceStreamingRequest",
  "CMsgRemoteDeviceStreamingRequest",
  "",
  sizeof(CMsgRemoteDeviceStreamingRequest),
  20,
  cmsg_remote_device_streaming_request__field_descriptors,
  cmsg_remote_device_streaming_request__field_indices_by_name,
  1,  cmsg_remote_device_streaming_request__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_streaming_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_streaming_cancel_request__field_descriptors[1] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingCancelRequest, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_streaming_cancel_request__field_indices_by_name[] = {
  0,   /* field[0] = request_id */
};
static const ProtobufCIntRange cmsg_remote_device_streaming_cancel_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_streaming_cancel_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamingCancelRequest",
  "CMsgRemoteDeviceStreamingCancelRequest",
  "CMsgRemoteDeviceStreamingCancelRequest",
  "",
  sizeof(CMsgRemoteDeviceStreamingCancelRequest),
  1,
  cmsg_remote_device_streaming_cancel_request__field_descriptors,
  cmsg_remote_device_streaming_cancel_request__field_indices_by_name,
  1,  cmsg_remote_device_streaming_cancel_request__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_streaming_cancel_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_streaming_progress__field_descriptors[2] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingProgress, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "progress",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CMsgRemoteDeviceStreamingProgress, has_progress),
    offsetof(CMsgRemoteDeviceStreamingProgress, progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_streaming_progress__field_indices_by_name[] = {
  1,   /* field[1] = progress */
  0,   /* field[0] = request_id */
};
static const ProtobufCIntRange cmsg_remote_device_streaming_progress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_streaming_progress__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamingProgress",
  "CMsgRemoteDeviceStreamingProgress",
  "CMsgRemoteDeviceStreamingProgress",
  "",
  sizeof(CMsgRemoteDeviceStreamingProgress),
  2,
  cmsg_remote_device_streaming_progress__field_descriptors,
  cmsg_remote_device_streaming_progress__field_indices_by_name,
  1,  cmsg_remote_device_streaming_progress__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_streaming_progress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const EStreamTransport cmsg_remote_device_streaming_response__transport__default_value = k_EStreamTransportUDP;
static const ProtobufCFieldDescriptor cmsg_remote_device_streaming_response__field_descriptors[7] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingResponse, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingResponse, result),
    &eremote_device_streaming_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceStreamingResponse, has_port),
    offsetof(CMsgRemoteDeviceStreamingResponse, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_session_key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceStreamingResponse, has_encrypted_session_key),
    offsetof(CMsgRemoteDeviceStreamingResponse, encrypted_session_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CMsgRemoteDeviceStreamingResponse, has_transport),
    offsetof(CMsgRemoteDeviceStreamingResponse, transport),
    &estream_transport__descriptor,
    &cmsg_remote_device_streaming_response__transport__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relay_server",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingResponse, relay_server),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceStreamingResponse, cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_streaming_response__field_indices_by_name[] = {
  6,   /* field[6] = cert */
  3,   /* field[3] = encrypted_session_key */
  2,   /* field[2] = port */
  5,   /* field[5] = relay_server */
  0,   /* field[0] = request_id */
  1,   /* field[1] = result */
  4,   /* field[4] = transport */
};
static const ProtobufCIntRange cmsg_remote_device_streaming_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_streaming_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamingResponse",
  "CMsgRemoteDeviceStreamingResponse",
  "CMsgRemoteDeviceStreamingResponse",
  "",
  sizeof(CMsgRemoteDeviceStreamingResponse),
  7,
  cmsg_remote_device_streaming_response__field_descriptors,
  cmsg_remote_device_streaming_response__field_indices_by_name,
  2,  cmsg_remote_device_streaming_response__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_streaming_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_proof_request__field_descriptors[2] =
{
  {
    "challenge",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceProofRequest, challenge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceProofRequest, has_request_id),
    offsetof(CMsgRemoteDeviceProofRequest, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_proof_request__field_indices_by_name[] = {
  0,   /* field[0] = challenge */
  1,   /* field[1] = request_id */
};
static const ProtobufCIntRange cmsg_remote_device_proof_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_proof_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceProofRequest",
  "CMsgRemoteDeviceProofRequest",
  "CMsgRemoteDeviceProofRequest",
  "",
  sizeof(CMsgRemoteDeviceProofRequest),
  2,
  cmsg_remote_device_proof_request__field_descriptors,
  cmsg_remote_device_proof_request__field_indices_by_name,
  1,  cmsg_remote_device_proof_request__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_proof_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_proof_response__field_descriptors[2] =
{
  {
    "response",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CMsgRemoteDeviceProofResponse, response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CMsgRemoteDeviceProofResponse, has_request_id),
    offsetof(CMsgRemoteDeviceProofResponse, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_proof_response__field_indices_by_name[] = {
  1,   /* field[1] = request_id */
  0,   /* field[0] = response */
};
static const ProtobufCIntRange cmsg_remote_device_proof_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_proof_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceProofResponse",
  "CMsgRemoteDeviceProofResponse",
  "CMsgRemoteDeviceProofResponse",
  "",
  sizeof(CMsgRemoteDeviceProofResponse),
  2,
  cmsg_remote_device_proof_response__field_descriptors,
  cmsg_remote_device_proof_response__field_indices_by_name,
  1,  cmsg_remote_device_proof_response__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_proof_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_remote_device_stream_transport_signal__field_descriptors[2] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceStreamTransportSignal, has_token),
    offsetof(CMsgRemoteDeviceStreamTransportSignal, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CMsgRemoteDeviceStreamTransportSignal, has_payload),
    offsetof(CMsgRemoteDeviceStreamTransportSignal, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_remote_device_stream_transport_signal__field_indices_by_name[] = {
  1,   /* field[1] = payload */
  0,   /* field[0] = token */
};
static const ProtobufCIntRange cmsg_remote_device_stream_transport_signal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmsg_remote_device_stream_transport_signal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CMsgRemoteDeviceStreamTransportSignal",
  "CMsgRemoteDeviceStreamTransportSignal",
  "CMsgRemoteDeviceStreamTransportSignal",
  "",
  sizeof(CMsgRemoteDeviceStreamTransportSignal),
  2,
  cmsg_remote_device_stream_transport_signal__field_descriptors,
  cmsg_remote_device_stream_transport_signal__field_indices_by_name,
  1,  cmsg_remote_device_stream_transport_signal__number_ranges,
  (ProtobufCMessageInit) cmsg_remote_device_stream_transport_signal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue eremote_client_broadcast_msg__enum_values_by_number[14] =
{
  { "k_ERemoteClientBroadcastMsgDiscovery", "k_ERemoteClientBroadcastMsgDiscovery", 0 },
  { "k_ERemoteClientBroadcastMsgStatus", "k_ERemoteClientBroadcastMsgStatus", 1 },
  { "k_ERemoteClientBroadcastMsgOffline", "k_ERemoteClientBroadcastMsgOffline", 2 },
  { "k_ERemoteDeviceAuthorizationRequest", "k_ERemoteDeviceAuthorizationRequest", 3 },
  { "k_ERemoteDeviceAuthorizationResponse", "k_ERemoteDeviceAuthorizationResponse", 4 },
  { "k_ERemoteDeviceStreamingRequest", "k_ERemoteDeviceStreamingRequest", 5 },
  { "k_ERemoteDeviceStreamingResponse", "k_ERemoteDeviceStreamingResponse", 6 },
  { "k_ERemoteDeviceProofRequest", "k_ERemoteDeviceProofRequest", 7 },
  { "k_ERemoteDeviceProofResponse", "k_ERemoteDeviceProofResponse", 8 },
  { "k_ERemoteDeviceAuthorizationCancelRequest", "k_ERemoteDeviceAuthorizationCancelRequest", 9 },
  { "k_ERemoteDeviceStreamingCancelRequest", "k_ERemoteDeviceStreamingCancelRequest", 10 },
  { "k_ERemoteClientBroadcastMsgClientIDDeconflict", "k_ERemoteClientBroadcastMsgClientIDDeconflict", 11 },
  { "k_ERemoteDeviceStreamTransportSignal", "k_ERemoteDeviceStreamTransportSignal", 12 },
  { "k_ERemoteDeviceStreamingProgress", "k_ERemoteDeviceStreamingProgress", 13 },
};
static const ProtobufCIntRange eremote_client_broadcast_msg__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex eremote_client_broadcast_msg__enum_values_by_name[14] =
{
  { "k_ERemoteClientBroadcastMsgClientIDDeconflict", 11 },
  { "k_ERemoteClientBroadcastMsgDiscovery", 0 },
  { "k_ERemoteClientBroadcastMsgOffline", 2 },
  { "k_ERemoteClientBroadcastMsgStatus", 1 },
  { "k_ERemoteDeviceAuthorizationCancelRequest", 9 },
  { "k_ERemoteDeviceAuthorizationRequest", 3 },
  { "k_ERemoteDeviceAuthorizationResponse", 4 },
  { "k_ERemoteDeviceProofRequest", 7 },
  { "k_ERemoteDeviceProofResponse", 8 },
  { "k_ERemoteDeviceStreamTransportSignal", 12 },
  { "k_ERemoteDeviceStreamingCancelRequest", 10 },
  { "k_ERemoteDeviceStreamingProgress", 13 },
  { "k_ERemoteDeviceStreamingRequest", 5 },
  { "k_ERemoteDeviceStreamingResponse", 6 },
};
const ProtobufCEnumDescriptor eremote_client_broadcast_msg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ERemoteClientBroadcastMsg",
  "ERemoteClientBroadcastMsg",
  "ERemoteClientBroadcastMsg",
  "",
  14,
  eremote_client_broadcast_msg__enum_values_by_number,
  14,
  eremote_client_broadcast_msg__enum_values_by_name,
  1,
  eremote_client_broadcast_msg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eremote_client_service__enum_values_by_number[5] =
{
  { "k_ERemoteClientServiceNone", "k_ERemoteClientServiceNone", 0 },
  { "k_ERemoteClientServiceRemoteControl", "k_ERemoteClientServiceRemoteControl", 1 },
  { "k_ERemoteClientServiceGameStreaming", "k_ERemoteClientServiceGameStreaming", 2 },
  { "k_ERemoteClientServiceSiteLicense", "k_ERemoteClientServiceSiteLicense", 4 },
  { "k_ERemoteClientServiceContentCache", "k_ERemoteClientServiceContentCache", 8 },
};
static const ProtobufCIntRange eremote_client_service__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{0, 5}
};
static const ProtobufCEnumValueIndex eremote_client_service__enum_values_by_name[5] =
{
  { "k_ERemoteClientServiceContentCache", 4 },
  { "k_ERemoteClientServiceGameStreaming", 2 },
  { "k_ERemoteClientServiceNone", 0 },
  { "k_ERemoteClientServiceRemoteControl", 1 },
  { "k_ERemoteClientServiceSiteLicense", 3 },
};
const ProtobufCEnumDescriptor eremote_client_service__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ERemoteClientService",
  "ERemoteClientService",
  "ERemoteClientService",
  "",
  5,
  eremote_client_service__enum_values_by_number,
  5,
  eremote_client_service__enum_values_by_name,
  3,
  eremote_client_service__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eremote_device_authorization_result__enum_values_by_number[9] =
{
  { "k_ERemoteDeviceAuthorizationSuccess", "k_ERemoteDeviceAuthorizationSuccess", 0 },
  { "k_ERemoteDeviceAuthorizationDenied", "k_ERemoteDeviceAuthorizationDenied", 1 },
  { "k_ERemoteDeviceAuthorizationNotLoggedIn", "k_ERemoteDeviceAuthorizationNotLoggedIn", 2 },
  { "k_ERemoteDeviceAuthorizationOffline", "k_ERemoteDeviceAuthorizationOffline", 3 },
  { "k_ERemoteDeviceAuthorizationBusy", "k_ERemoteDeviceAuthorizationBusy", 4 },
  { "k_ERemoteDeviceAuthorizationInProgress", "k_ERemoteDeviceAuthorizationInProgress", 5 },
  { "k_ERemoteDeviceAuthorizationTimedOut", "k_ERemoteDeviceAuthorizationTimedOut", 6 },
  { "k_ERemoteDeviceAuthorizationFailed", "k_ERemoteDeviceAuthorizationFailed", 7 },
  { "k_ERemoteDeviceAuthorizationCanceled", "k_ERemoteDeviceAuthorizationCanceled", 8 },
};
static const ProtobufCIntRange eremote_device_authorization_result__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex eremote_device_authorization_result__enum_values_by_name[9] =
{
  { "k_ERemoteDeviceAuthorizationBusy", 4 },
  { "k_ERemoteDeviceAuthorizationCanceled", 8 },
  { "k_ERemoteDeviceAuthorizationDenied", 1 },
  { "k_ERemoteDeviceAuthorizationFailed", 7 },
  { "k_ERemoteDeviceAuthorizationInProgress", 5 },
  { "k_ERemoteDeviceAuthorizationNotLoggedIn", 2 },
  { "k_ERemoteDeviceAuthorizationOffline", 3 },
  { "k_ERemoteDeviceAuthorizationSuccess", 0 },
  { "k_ERemoteDeviceAuthorizationTimedOut", 6 },
};
const ProtobufCEnumDescriptor eremote_device_authorization_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ERemoteDeviceAuthorizationResult",
  "ERemoteDeviceAuthorizationResult",
  "ERemoteDeviceAuthorizationResult",
  "",
  9,
  eremote_device_authorization_result__enum_values_by_number,
  9,
  eremote_device_authorization_result__enum_values_by_name,
  1,
  eremote_device_authorization_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estream_device_form_factor__enum_values_by_number[5] =
{
  { "k_EStreamDeviceFormFactorUnknown", "k_EStreamDeviceFormFactorUnknown", 0 },
  { "k_EStreamDeviceFormFactorPhone", "k_EStreamDeviceFormFactorPhone", 1 },
  { "k_EStreamDeviceFormFactorTablet", "k_EStreamDeviceFormFactorTablet", 2 },
  { "k_EStreamDeviceFormFactorComputer", "k_EStreamDeviceFormFactorComputer", 3 },
  { "k_EStreamDeviceFormFactorTV", "k_EStreamDeviceFormFactorTV", 4 },
};
static const ProtobufCIntRange estream_device_form_factor__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex estream_device_form_factor__enum_values_by_name[5] =
{
  { "k_EStreamDeviceFormFactorComputer", 3 },
  { "k_EStreamDeviceFormFactorPhone", 1 },
  { "k_EStreamDeviceFormFactorTV", 4 },
  { "k_EStreamDeviceFormFactorTablet", 2 },
  { "k_EStreamDeviceFormFactorUnknown", 0 },
};
const ProtobufCEnumDescriptor estream_device_form_factor__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStreamDeviceFormFactor",
  "EStreamDeviceFormFactor",
  "EStreamDeviceFormFactor",
  "",
  5,
  estream_device_form_factor__enum_values_by_number,
  5,
  estream_device_form_factor__enum_values_by_name,
  1,
  estream_device_form_factor__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estream_transport__enum_values_by_number[7] =
{
  { "k_EStreamTransportNone", "k_EStreamTransportNone", 0 },
  { "k_EStreamTransportUDP", "k_EStreamTransportUDP", 1 },
  { "k_EStreamTransportUDPRelay", "k_EStreamTransportUDPRelay", 2 },
  { "k_EStreamTransportWebRTC", "k_EStreamTransportWebRTC", 3 },
  { "k_EStreamTransportSDR", "k_EStreamTransportSDR", 4 },
  { "k_EStreamTransportUDP_SNS", "k_EStreamTransportUDP_SNS", 5 },
  { "k_EStreamTransportUDPRelay_SNS", "k_EStreamTransportUDPRelay_SNS", 6 },
};
static const ProtobufCIntRange estream_transport__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex estream_transport__enum_values_by_name[7] =
{
  { "k_EStreamTransportNone", 0 },
  { "k_EStreamTransportSDR", 4 },
  { "k_EStreamTransportUDP", 1 },
  { "k_EStreamTransportUDPRelay", 2 },
  { "k_EStreamTransportUDPRelay_SNS", 6 },
  { "k_EStreamTransportUDP_SNS", 5 },
  { "k_EStreamTransportWebRTC", 3 },
};
const ProtobufCEnumDescriptor estream_transport__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStreamTransport",
  "EStreamTransport",
  "EStreamTransport",
  "",
  7,
  estream_transport__enum_values_by_number,
  7,
  estream_transport__enum_values_by_name,
  1,
  estream_transport__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue estream_interface__enum_values_by_number[4] =
{
  { "k_EStreamInterfaceDefault", "k_EStreamInterfaceDefault", 0 },
  { "k_EStreamInterfaceRecentGames", "k_EStreamInterfaceRecentGames", 1 },
  { "k_EStreamInterfaceBigPicture", "k_EStreamInterfaceBigPicture", 2 },
  { "k_EStreamInterfaceDesktop", "k_EStreamInterfaceDesktop", 3 },
};
static const ProtobufCIntRange estream_interface__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex estream_interface__enum_values_by_name[4] =
{
  { "k_EStreamInterfaceBigPicture", 2 },
  { "k_EStreamInterfaceDefault", 0 },
  { "k_EStreamInterfaceDesktop", 3 },
  { "k_EStreamInterfaceRecentGames", 1 },
};
const ProtobufCEnumDescriptor estream_interface__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EStreamInterface",
  "EStreamInterface",
  "EStreamInterface",
  "",
  4,
  estream_interface__enum_values_by_number,
  4,
  estream_interface__enum_values_by_name,
  1,
  estream_interface__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue eremote_device_streaming_result__enum_values_by_number[15] =
{
  { "k_ERemoteDeviceStreamingSuccess", "k_ERemoteDeviceStreamingSuccess", 0 },
  { "k_ERemoteDeviceStreamingUnauthorized", "k_ERemoteDeviceStreamingUnauthorized", 1 },
  { "k_ERemoteDeviceStreamingScreenLocked", "k_ERemoteDeviceStreamingScreenLocked", 2 },
  { "k_ERemoteDeviceStreamingFailed", "k_ERemoteDeviceStreamingFailed", 3 },
  { "k_ERemoteDeviceStreamingBusy", "k_ERemoteDeviceStreamingBusy", 4 },
  { "k_ERemoteDeviceStreamingInProgress", "k_ERemoteDeviceStreamingInProgress", 5 },
  { "k_ERemoteDeviceStreamingCanceled", "k_ERemoteDeviceStreamingCanceled", 6 },
  { "k_ERemoteDeviceStreamingDriversNotInstalled", "k_ERemoteDeviceStreamingDriversNotInstalled", 7 },
  { "k_ERemoteDeviceStreamingDisabled", "k_ERemoteDeviceStreamingDisabled", 8 },
  { "k_ERemoteDeviceStreamingBroadcastingActive", "k_ERemoteDeviceStreamingBroadcastingActive", 9 },
  { "k_ERemoteDeviceStreamingVRActive", "k_ERemoteDeviceStreamingVRActive", 10 },
  { "k_ERemoteDeviceStreamingPINRequired", "k_ERemoteDeviceStreamingPINRequired", 11 },
  { "k_ERemoteDeviceStreamingTransportUnavailable", "k_ERemoteDeviceStreamingTransportUnavailable", 12 },
  { "k_ERemoteDeviceStreamingInvisible", "k_ERemoteDeviceStreamingInvisible", 13 },
  { "k_ERemoteDeviceStreamingGameLaunchFailed", "k_ERemoteDeviceStreamingGameLaunchFailed", 14 },
};
static const ProtobufCIntRange eremote_device_streaming_result__value_ranges[] = {
{0, 0},{0, 15}
};
static const ProtobufCEnumValueIndex eremote_device_streaming_result__enum_values_by_name[15] =
{
  { "k_ERemoteDeviceStreamingBroadcastingActive", 9 },
  { "k_ERemoteDeviceStreamingBusy", 4 },
  { "k_ERemoteDeviceStreamingCanceled", 6 },
  { "k_ERemoteDeviceStreamingDisabled", 8 },
  { "k_ERemoteDeviceStreamingDriversNotInstalled", 7 },
  { "k_ERemoteDeviceStreamingFailed", 3 },
  { "k_ERemoteDeviceStreamingGameLaunchFailed", 14 },
  { "k_ERemoteDeviceStreamingInProgress", 5 },
  { "k_ERemoteDeviceStreamingInvisible", 13 },
  { "k_ERemoteDeviceStreamingPINRequired", 11 },
  { "k_ERemoteDeviceStreamingScreenLocked", 2 },
  { "k_ERemoteDeviceStreamingSuccess", 0 },
  { "k_ERemoteDeviceStreamingTransportUnavailable", 12 },
  { "k_ERemoteDeviceStreamingUnauthorized", 1 },
  { "k_ERemoteDeviceStreamingVRActive", 10 },
};
const ProtobufCEnumDescriptor eremote_device_streaming_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ERemoteDeviceStreamingResult",
  "ERemoteDeviceStreamingResult",
  "ERemoteDeviceStreamingResult",
  "",
  15,
  eremote_device_streaming_result__enum_values_by_number,
  15,
  eremote_device_streaming_result__enum_values_by_name,
  1,
  eremote_device_streaming_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
