/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/hiddevices.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf/hiddevices.pb-c.h"
void   chiddevice_info__init
                     (CHIDDeviceInfo         *message)
{
  static const CHIDDeviceInfo init_value = CHIDDEVICE_INFO__INIT;
  *message = init_value;
}
size_t chiddevice_info__get_packed_size
                     (const CHIDDeviceInfo *message)
{
  assert(message->base.descriptor == &chiddevice_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chiddevice_info__pack
                     (const CHIDDeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chiddevice_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chiddevice_info__pack_to_buffer
                     (const CHIDDeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chiddevice_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CHIDDeviceInfo *
       chiddevice_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CHIDDeviceInfo *)
     protobuf_c_message_unpack (&chiddevice_info__descriptor,
                                allocator, len, data);
}
void   chiddevice_info__free_unpacked
                     (CHIDDeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chiddevice_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chiddevice_input_report__init
                     (CHIDDeviceInputReport         *message)
{
  static const CHIDDeviceInputReport init_value = CHIDDEVICE_INPUT_REPORT__INIT;
  *message = init_value;
}
size_t chiddevice_input_report__get_packed_size
                     (const CHIDDeviceInputReport *message)
{
  assert(message->base.descriptor == &chiddevice_input_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chiddevice_input_report__pack
                     (const CHIDDeviceInputReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chiddevice_input_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chiddevice_input_report__pack_to_buffer
                     (const CHIDDeviceInputReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chiddevice_input_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CHIDDeviceInputReport *
       chiddevice_input_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CHIDDeviceInputReport *)
     protobuf_c_message_unpack (&chiddevice_input_report__descriptor,
                                allocator, len, data);
}
void   chiddevice_input_report__free_unpacked
                     (CHIDDeviceInputReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chiddevice_input_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chidmessage_to_remote__device_open__init
                     (CHIDMessageToRemote__DeviceOpen         *message)
{
  static const CHIDMessageToRemote__DeviceOpen init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_OPEN__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_close__init
                     (CHIDMessageToRemote__DeviceClose         *message)
{
  static const CHIDMessageToRemote__DeviceClose init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_CLOSE__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_write__init
                     (CHIDMessageToRemote__DeviceWrite         *message)
{
  static const CHIDMessageToRemote__DeviceWrite init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_WRITE__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_read__init
                     (CHIDMessageToRemote__DeviceRead         *message)
{
  static const CHIDMessageToRemote__DeviceRead init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_READ__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_send_feature_report__init
                     (CHIDMessageToRemote__DeviceSendFeatureReport         *message)
{
  static const CHIDMessageToRemote__DeviceSendFeatureReport init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_SEND_FEATURE_REPORT__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_get_feature_report__init
                     (CHIDMessageToRemote__DeviceGetFeatureReport         *message)
{
  static const CHIDMessageToRemote__DeviceGetFeatureReport init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_GET_FEATURE_REPORT__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_get_vendor_string__init
                     (CHIDMessageToRemote__DeviceGetVendorString         *message)
{
  static const CHIDMessageToRemote__DeviceGetVendorString init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_GET_VENDOR_STRING__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_get_product_string__init
                     (CHIDMessageToRemote__DeviceGetProductString         *message)
{
  static const CHIDMessageToRemote__DeviceGetProductString init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_GET_PRODUCT_STRING__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_get_serial_number_string__init
                     (CHIDMessageToRemote__DeviceGetSerialNumberString         *message)
{
  static const CHIDMessageToRemote__DeviceGetSerialNumberString init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_GET_SERIAL_NUMBER_STRING__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_start_input_reports__init
                     (CHIDMessageToRemote__DeviceStartInputReports         *message)
{
  static const CHIDMessageToRemote__DeviceStartInputReports init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_START_INPUT_REPORTS__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_request_full_report__init
                     (CHIDMessageToRemote__DeviceRequestFullReport         *message)
{
  static const CHIDMessageToRemote__DeviceRequestFullReport init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_REQUEST_FULL_REPORT__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__device_disconnect__init
                     (CHIDMessageToRemote__DeviceDisconnect         *message)
{
  static const CHIDMessageToRemote__DeviceDisconnect init_value = CHIDMESSAGE_TO_REMOTE__DEVICE_DISCONNECT__INIT;
  *message = init_value;
}
void   chidmessage_to_remote__init
                     (CHIDMessageToRemote         *message)
{
  static const CHIDMessageToRemote init_value = CHIDMESSAGE_TO_REMOTE__INIT;
  *message = init_value;
}
size_t chidmessage_to_remote__get_packed_size
                     (const CHIDMessageToRemote *message)
{
  assert(message->base.descriptor == &chidmessage_to_remote__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chidmessage_to_remote__pack
                     (const CHIDMessageToRemote *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chidmessage_to_remote__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chidmessage_to_remote__pack_to_buffer
                     (const CHIDMessageToRemote *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chidmessage_to_remote__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CHIDMessageToRemote *
       chidmessage_to_remote__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CHIDMessageToRemote *)
     protobuf_c_message_unpack (&chidmessage_to_remote__descriptor,
                                allocator, len, data);
}
void   chidmessage_to_remote__free_unpacked
                     (CHIDMessageToRemote *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chidmessage_to_remote__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chidmessage_from_remote__update_device_list__init
                     (CHIDMessageFromRemote__UpdateDeviceList         *message)
{
  static const CHIDMessageFromRemote__UpdateDeviceList init_value = CHIDMESSAGE_FROM_REMOTE__UPDATE_DEVICE_LIST__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__request_response__init
                     (CHIDMessageFromRemote__RequestResponse         *message)
{
  static const CHIDMessageFromRemote__RequestResponse init_value = CHIDMESSAGE_FROM_REMOTE__REQUEST_RESPONSE__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__device_input_reports__device_input_report__init
                     (CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport         *message)
{
  static const CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport init_value = CHIDMESSAGE_FROM_REMOTE__DEVICE_INPUT_REPORTS__DEVICE_INPUT_REPORT__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__device_input_reports__init
                     (CHIDMessageFromRemote__DeviceInputReports         *message)
{
  static const CHIDMessageFromRemote__DeviceInputReports init_value = CHIDMESSAGE_FROM_REMOTE__DEVICE_INPUT_REPORTS__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__close_device__init
                     (CHIDMessageFromRemote__CloseDevice         *message)
{
  static const CHIDMessageFromRemote__CloseDevice init_value = CHIDMESSAGE_FROM_REMOTE__CLOSE_DEVICE__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__close_all_devices__init
                     (CHIDMessageFromRemote__CloseAllDevices         *message)
{
  static const CHIDMessageFromRemote__CloseAllDevices init_value = CHIDMESSAGE_FROM_REMOTE__CLOSE_ALL_DEVICES__INIT;
  *message = init_value;
}
void   chidmessage_from_remote__init
                     (CHIDMessageFromRemote         *message)
{
  static const CHIDMessageFromRemote init_value = CHIDMESSAGE_FROM_REMOTE__INIT;
  *message = init_value;
}
size_t chidmessage_from_remote__get_packed_size
                     (const CHIDMessageFromRemote *message)
{
  assert(message->base.descriptor == &chidmessage_from_remote__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chidmessage_from_remote__pack
                     (const CHIDMessageFromRemote *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chidmessage_from_remote__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chidmessage_from_remote__pack_to_buffer
                     (const CHIDMessageFromRemote *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chidmessage_from_remote__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CHIDMessageFromRemote *
       chidmessage_from_remote__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CHIDMessageFromRemote *)
     protobuf_c_message_unpack (&chidmessage_from_remote__descriptor,
                                allocator, len, data);
}
void   chidmessage_from_remote__free_unpacked
                     (CHIDMessageFromRemote *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chidmessage_from_remote__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const int32_t chiddevice_info__interface_number__default_value = -1;
static const int32_t chiddevice_info__ostype__default_value = -1;
static const uint32_t chiddevice_info__e_controller_type__default_value = 0u;
static const protobuf_c_boolean chiddevice_info__is_xinput_device__default_value = 0;
static const ProtobufCFieldDescriptor chiddevice_info__field_descriptors[19] =
{
  {
    "location",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CHIDDeviceInfo, has_location),
    offsetof(CHIDDeviceInfo, location),
    &ehiddevice_location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CHIDDeviceInfo, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_vendor_id),
    offsetof(CHIDDeviceInfo, vendor_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_product_id),
    offsetof(CHIDDeviceInfo, product_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CHIDDeviceInfo, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "release_number",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_release_number),
    offsetof(CHIDDeviceInfo, release_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manufacturer_string",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CHIDDeviceInfo, manufacturer_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product_string",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CHIDDeviceInfo, product_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usage_page",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_usage_page),
    offsetof(CHIDDeviceInfo, usage_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usage",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_usage),
    offsetof(CHIDDeviceInfo, usage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_number",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CHIDDeviceInfo, has_interface_number),
    offsetof(CHIDDeviceInfo, interface_number),
    NULL,
    &chiddevice_info__interface_number__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ostype",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CHIDDeviceInfo, has_ostype),
    offsetof(CHIDDeviceInfo, ostype),
    NULL,
    &chiddevice_info__ostype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_generic_gamepad",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CHIDDeviceInfo, has_is_generic_gamepad),
    offsetof(CHIDDeviceInfo, is_generic_gamepad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_generic_joystick",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CHIDDeviceInfo, has_is_generic_joystick),
    offsetof(CHIDDeviceInfo, is_generic_joystick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "caps_bits",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_caps_bits),
    offsetof(CHIDDeviceInfo, caps_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_session_id),
    offsetof(CHIDDeviceInfo, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eControllerType",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_econtrollertype),
    offsetof(CHIDDeviceInfo, econtrollertype),
    NULL,
    &chiddevice_info__e_controller_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_xinput_device",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CHIDDeviceInfo, has_is_xinput_device),
    offsetof(CHIDDeviceInfo, is_xinput_device),
    NULL,
    &chiddevice_info__is_xinput_device__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_remote_play_together_appid",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInfo, has_session_remote_play_together_appid),
    offsetof(CHIDDeviceInfo, session_remote_play_together_appid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chiddevice_info__field_indices_by_name[] = {
  14,   /* field[14] = caps_bits */
  16,   /* field[16] = eControllerType */
  10,   /* field[10] = interface_number */
  12,   /* field[12] = is_generic_gamepad */
  13,   /* field[13] = is_generic_joystick */
  17,   /* field[17] = is_xinput_device */
  0,   /* field[0] = location */
  6,   /* field[6] = manufacturer_string */
  11,   /* field[11] = ostype */
  1,   /* field[1] = path */
  3,   /* field[3] = product_id */
  7,   /* field[7] = product_string */
  5,   /* field[5] = release_number */
  4,   /* field[4] = serial_number */
  15,   /* field[15] = session_id */
  18,   /* field[18] = session_remote_play_together_appid */
  9,   /* field[9] = usage */
  8,   /* field[8] = usage_page */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange chiddevice_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor chiddevice_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDDeviceInfo",
  "CHIDDeviceInfo",
  "CHIDDeviceInfo",
  "",
  sizeof(CHIDDeviceInfo),
  19,
  chiddevice_info__field_descriptors,
  chiddevice_info__field_indices_by_name,
  1,  chiddevice_info__number_ranges,
  (ProtobufCMessageInit) chiddevice_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chiddevice_input_report__field_descriptors[4] =
{
  {
    "full_report",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDDeviceInputReport, has_full_report),
    offsetof(CHIDDeviceInputReport, full_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta_report",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDDeviceInputReport, has_delta_report),
    offsetof(CHIDDeviceInputReport, delta_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta_report_size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInputReport, has_delta_report_size),
    offsetof(CHIDDeviceInputReport, delta_report_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta_report_crc",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDDeviceInputReport, has_delta_report_crc),
    offsetof(CHIDDeviceInputReport, delta_report_crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chiddevice_input_report__field_indices_by_name[] = {
  1,   /* field[1] = delta_report */
  3,   /* field[3] = delta_report_crc */
  2,   /* field[2] = delta_report_size */
  0,   /* field[0] = full_report */
};
static const ProtobufCIntRange chiddevice_input_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor chiddevice_input_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDDeviceInputReport",
  "CHIDDeviceInputReport",
  "CHIDDeviceInputReport",
  "",
  sizeof(CHIDDeviceInputReport),
  4,
  chiddevice_input_report__field_descriptors,
  chiddevice_input_report__field_indices_by_name,
  1,  chiddevice_input_report__number_ranges,
  (ProtobufCMessageInit) chiddevice_input_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_open__field_descriptors[1] =
{
  {
    "info",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CHIDMessageToRemote__DeviceOpen, info),
    &chiddevice_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_open__field_indices_by_name[] = {
  0,   /* field[0] = info */
};
static const ProtobufCIntRange chidmessage_to_remote__device_open__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_open__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceOpen",
  "DeviceOpen",
  "CHIDMessageToRemote__DeviceOpen",
  "",
  sizeof(CHIDMessageToRemote__DeviceOpen),
  1,
  chidmessage_to_remote__device_open__field_descriptors,
  chidmessage_to_remote__device_open__field_indices_by_name,
  1,  chidmessage_to_remote__device_open__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_open__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_close__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceClose, has_device),
    offsetof(CHIDMessageToRemote__DeviceClose, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_close__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_close__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceClose",
  "DeviceClose",
  "CHIDMessageToRemote__DeviceClose",
  "",
  sizeof(CHIDMessageToRemote__DeviceClose),
  1,
  chidmessage_to_remote__device_close__field_descriptors,
  chidmessage_to_remote__device_close__field_indices_by_name,
  1,  chidmessage_to_remote__device_close__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_write__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceWrite, has_device),
    offsetof(CHIDMessageToRemote__DeviceWrite, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDMessageToRemote__DeviceWrite, has_data),
    offsetof(CHIDMessageToRemote__DeviceWrite, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_write__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_write__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_write__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceWrite",
  "DeviceWrite",
  "CHIDMessageToRemote__DeviceWrite",
  "",
  sizeof(CHIDMessageToRemote__DeviceWrite),
  2,
  chidmessage_to_remote__device_write__field_descriptors,
  chidmessage_to_remote__device_write__field_indices_by_name,
  1,  chidmessage_to_remote__device_write__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_write__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_read__field_descriptors[3] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceRead, has_device),
    offsetof(CHIDMessageToRemote__DeviceRead, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceRead, has_length),
    offsetof(CHIDMessageToRemote__DeviceRead, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout_ms",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CHIDMessageToRemote__DeviceRead, has_timeout_ms),
    offsetof(CHIDMessageToRemote__DeviceRead, timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_read__field_indices_by_name[] = {
  0,   /* field[0] = device */
  1,   /* field[1] = length */
  2,   /* field[2] = timeout_ms */
};
static const ProtobufCIntRange chidmessage_to_remote__device_read__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_read__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceRead",
  "DeviceRead",
  "CHIDMessageToRemote__DeviceRead",
  "",
  sizeof(CHIDMessageToRemote__DeviceRead),
  3,
  chidmessage_to_remote__device_read__field_descriptors,
  chidmessage_to_remote__device_read__field_indices_by_name,
  1,  chidmessage_to_remote__device_read__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_read__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_send_feature_report__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceSendFeatureReport, has_device),
    offsetof(CHIDMessageToRemote__DeviceSendFeatureReport, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDMessageToRemote__DeviceSendFeatureReport, has_data),
    offsetof(CHIDMessageToRemote__DeviceSendFeatureReport, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_send_feature_report__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_send_feature_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_send_feature_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceSendFeatureReport",
  "DeviceSendFeatureReport",
  "CHIDMessageToRemote__DeviceSendFeatureReport",
  "",
  sizeof(CHIDMessageToRemote__DeviceSendFeatureReport),
  2,
  chidmessage_to_remote__device_send_feature_report__field_descriptors,
  chidmessage_to_remote__device_send_feature_report__field_indices_by_name,
  1,  chidmessage_to_remote__device_send_feature_report__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_send_feature_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_get_feature_report__field_descriptors[3] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, has_device),
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "report_number",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, has_report_number),
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, report_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, has_length),
    offsetof(CHIDMessageToRemote__DeviceGetFeatureReport, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_get_feature_report__field_indices_by_name[] = {
  0,   /* field[0] = device */
  2,   /* field[2] = length */
  1,   /* field[1] = report_number */
};
static const ProtobufCIntRange chidmessage_to_remote__device_get_feature_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_get_feature_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceGetFeatureReport",
  "DeviceGetFeatureReport",
  "CHIDMessageToRemote__DeviceGetFeatureReport",
  "",
  sizeof(CHIDMessageToRemote__DeviceGetFeatureReport),
  3,
  chidmessage_to_remote__device_get_feature_report__field_descriptors,
  chidmessage_to_remote__device_get_feature_report__field_indices_by_name,
  1,  chidmessage_to_remote__device_get_feature_report__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_get_feature_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_get_vendor_string__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceGetVendorString, has_device),
    offsetof(CHIDMessageToRemote__DeviceGetVendorString, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_get_vendor_string__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_get_vendor_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_get_vendor_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceGetVendorString",
  "DeviceGetVendorString",
  "CHIDMessageToRemote__DeviceGetVendorString",
  "",
  sizeof(CHIDMessageToRemote__DeviceGetVendorString),
  1,
  chidmessage_to_remote__device_get_vendor_string__field_descriptors,
  chidmessage_to_remote__device_get_vendor_string__field_indices_by_name,
  1,  chidmessage_to_remote__device_get_vendor_string__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_get_vendor_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_get_product_string__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceGetProductString, has_device),
    offsetof(CHIDMessageToRemote__DeviceGetProductString, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_get_product_string__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_get_product_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_get_product_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceGetProductString",
  "DeviceGetProductString",
  "CHIDMessageToRemote__DeviceGetProductString",
  "",
  sizeof(CHIDMessageToRemote__DeviceGetProductString),
  1,
  chidmessage_to_remote__device_get_product_string__field_descriptors,
  chidmessage_to_remote__device_get_product_string__field_indices_by_name,
  1,  chidmessage_to_remote__device_get_product_string__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_get_product_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_get_serial_number_string__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceGetSerialNumberString, has_device),
    offsetof(CHIDMessageToRemote__DeviceGetSerialNumberString, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_get_serial_number_string__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_get_serial_number_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_get_serial_number_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceGetSerialNumberString",
  "DeviceGetSerialNumberString",
  "CHIDMessageToRemote__DeviceGetSerialNumberString",
  "",
  sizeof(CHIDMessageToRemote__DeviceGetSerialNumberString),
  1,
  chidmessage_to_remote__device_get_serial_number_string__field_descriptors,
  chidmessage_to_remote__device_get_serial_number_string__field_indices_by_name,
  1,  chidmessage_to_remote__device_get_serial_number_string__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_get_serial_number_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_start_input_reports__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceStartInputReports, has_device),
    offsetof(CHIDMessageToRemote__DeviceStartInputReports, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceStartInputReports, has_length),
    offsetof(CHIDMessageToRemote__DeviceStartInputReports, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_start_input_reports__field_indices_by_name[] = {
  0,   /* field[0] = device */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange chidmessage_to_remote__device_start_input_reports__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_start_input_reports__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceStartInputReports",
  "DeviceStartInputReports",
  "CHIDMessageToRemote__DeviceStartInputReports",
  "",
  sizeof(CHIDMessageToRemote__DeviceStartInputReports),
  2,
  chidmessage_to_remote__device_start_input_reports__field_descriptors,
  chidmessage_to_remote__device_start_input_reports__field_indices_by_name,
  1,  chidmessage_to_remote__device_start_input_reports__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_start_input_reports__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_request_full_report__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceRequestFullReport, has_device),
    offsetof(CHIDMessageToRemote__DeviceRequestFullReport, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_request_full_report__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_to_remote__device_request_full_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_request_full_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceRequestFullReport",
  "DeviceRequestFullReport",
  "CHIDMessageToRemote__DeviceRequestFullReport",
  "",
  sizeof(CHIDMessageToRemote__DeviceRequestFullReport),
  1,
  chidmessage_to_remote__device_request_full_report__field_descriptors,
  chidmessage_to_remote__device_request_full_report__field_indices_by_name,
  1,  chidmessage_to_remote__device_request_full_report__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_request_full_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__device_disconnect__field_descriptors[3] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote__DeviceDisconnect, has_device),
    offsetof(CHIDMessageToRemote__DeviceDisconnect, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnectMethod",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CHIDMessageToRemote__DeviceDisconnect, has_disconnectmethod),
    offsetof(CHIDMessageToRemote__DeviceDisconnect, disconnectmethod),
    &ehiddevice_disconnect_method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDMessageToRemote__DeviceDisconnect, has_data),
    offsetof(CHIDMessageToRemote__DeviceDisconnect, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__device_disconnect__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = device */
  1,   /* field[1] = disconnectMethod */
};
static const ProtobufCIntRange chidmessage_to_remote__device_disconnect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__device_disconnect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote.DeviceDisconnect",
  "DeviceDisconnect",
  "CHIDMessageToRemote__DeviceDisconnect",
  "",
  sizeof(CHIDMessageToRemote__DeviceDisconnect),
  3,
  chidmessage_to_remote__device_disconnect__field_descriptors,
  chidmessage_to_remote__device_disconnect__field_indices_by_name,
  1,  chidmessage_to_remote__device_disconnect__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__device_disconnect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_to_remote__field_descriptors[13] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageToRemote, has_request_id),
    offsetof(CHIDMessageToRemote, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_open",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_open),
    &chidmessage_to_remote__device_open__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_close",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_close),
    &chidmessage_to_remote__device_close__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_write",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_write),
    &chidmessage_to_remote__device_write__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_read",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_read),
    &chidmessage_to_remote__device_read__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_send_feature_report",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_send_feature_report),
    &chidmessage_to_remote__device_send_feature_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_get_feature_report",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_get_feature_report),
    &chidmessage_to_remote__device_get_feature_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_get_vendor_string",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_get_vendor_string),
    &chidmessage_to_remote__device_get_vendor_string__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_get_product_string",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_get_product_string),
    &chidmessage_to_remote__device_get_product_string__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_get_serial_number_string",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_get_serial_number_string),
    &chidmessage_to_remote__device_get_serial_number_string__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_start_input_reports",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_start_input_reports),
    &chidmessage_to_remote__device_start_input_reports__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_request_full_report",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_request_full_report),
    &chidmessage_to_remote__device_request_full_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_disconnect",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageToRemote, command_case),
    offsetof(CHIDMessageToRemote, device_disconnect),
    &chidmessage_to_remote__device_disconnect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_to_remote__field_indices_by_name[] = {
  2,   /* field[2] = device_close */
  12,   /* field[12] = device_disconnect */
  6,   /* field[6] = device_get_feature_report */
  8,   /* field[8] = device_get_product_string */
  9,   /* field[9] = device_get_serial_number_string */
  7,   /* field[7] = device_get_vendor_string */
  1,   /* field[1] = device_open */
  4,   /* field[4] = device_read */
  11,   /* field[11] = device_request_full_report */
  5,   /* field[5] = device_send_feature_report */
  10,   /* field[10] = device_start_input_reports */
  3,   /* field[3] = device_write */
  0,   /* field[0] = request_id */
};
static const ProtobufCIntRange chidmessage_to_remote__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor chidmessage_to_remote__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageToRemote",
  "CHIDMessageToRemote",
  "CHIDMessageToRemote",
  "",
  sizeof(CHIDMessageToRemote),
  13,
  chidmessage_to_remote__field_descriptors,
  chidmessage_to_remote__field_indices_by_name,
  1,  chidmessage_to_remote__number_ranges,
  (ProtobufCMessageInit) chidmessage_to_remote__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__update_device_list__field_descriptors[1] =
{
  {
    "devices",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote__UpdateDeviceList, n_devices),
    offsetof(CHIDMessageFromRemote__UpdateDeviceList, devices),
    &chiddevice_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__update_device_list__field_indices_by_name[] = {
  0,   /* field[0] = devices */
};
static const ProtobufCIntRange chidmessage_from_remote__update_device_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__update_device_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.UpdateDeviceList",
  "UpdateDeviceList",
  "CHIDMessageFromRemote__UpdateDeviceList",
  "",
  sizeof(CHIDMessageFromRemote__UpdateDeviceList),
  1,
  chidmessage_from_remote__update_device_list__field_descriptors,
  chidmessage_from_remote__update_device_list__field_indices_by_name,
  1,  chidmessage_from_remote__update_device_list__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__update_device_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__request_response__field_descriptors[3] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageFromRemote__RequestResponse, has_request_id),
    offsetof(CHIDMessageFromRemote__RequestResponse, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CHIDMessageFromRemote__RequestResponse, has_result),
    offsetof(CHIDMessageFromRemote__RequestResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CHIDMessageFromRemote__RequestResponse, has_data),
    offsetof(CHIDMessageFromRemote__RequestResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__request_response__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = request_id */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange chidmessage_from_remote__request_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__request_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.RequestResponse",
  "RequestResponse",
  "CHIDMessageFromRemote__RequestResponse",
  "",
  sizeof(CHIDMessageFromRemote__RequestResponse),
  3,
  chidmessage_from_remote__request_response__field_descriptors,
  chidmessage_from_remote__request_response__field_indices_by_name,
  1,  chidmessage_from_remote__request_response__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__request_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__device_input_reports__device_input_report__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport, has_device),
    offsetof(CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reports",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport, n_reports),
    offsetof(CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport, reports),
    &chiddevice_input_report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__device_input_reports__device_input_report__field_indices_by_name[] = {
  0,   /* field[0] = device */
  1,   /* field[1] = reports */
};
static const ProtobufCIntRange chidmessage_from_remote__device_input_reports__device_input_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__device_input_reports__device_input_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.DeviceInputReports.DeviceInputReport",
  "DeviceInputReport",
  "CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport",
  "",
  sizeof(CHIDMessageFromRemote__DeviceInputReports__DeviceInputReport),
  2,
  chidmessage_from_remote__device_input_reports__device_input_report__field_descriptors,
  chidmessage_from_remote__device_input_reports__device_input_report__field_indices_by_name,
  1,  chidmessage_from_remote__device_input_reports__device_input_report__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__device_input_reports__device_input_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__device_input_reports__field_descriptors[1] =
{
  {
    "device_reports",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote__DeviceInputReports, n_device_reports),
    offsetof(CHIDMessageFromRemote__DeviceInputReports, device_reports),
    &chidmessage_from_remote__device_input_reports__device_input_report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__device_input_reports__field_indices_by_name[] = {
  0,   /* field[0] = device_reports */
};
static const ProtobufCIntRange chidmessage_from_remote__device_input_reports__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__device_input_reports__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.DeviceInputReports",
  "DeviceInputReports",
  "CHIDMessageFromRemote__DeviceInputReports",
  "",
  sizeof(CHIDMessageFromRemote__DeviceInputReports),
  1,
  chidmessage_from_remote__device_input_reports__field_descriptors,
  chidmessage_from_remote__device_input_reports__field_indices_by_name,
  1,  chidmessage_from_remote__device_input_reports__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__device_input_reports__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__close_device__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CHIDMessageFromRemote__CloseDevice, has_device),
    offsetof(CHIDMessageFromRemote__CloseDevice, device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__close_device__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange chidmessage_from_remote__close_device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__close_device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.CloseDevice",
  "CloseDevice",
  "CHIDMessageFromRemote__CloseDevice",
  "",
  sizeof(CHIDMessageFromRemote__CloseDevice),
  1,
  chidmessage_from_remote__close_device__field_descriptors,
  chidmessage_from_remote__close_device__field_indices_by_name,
  1,  chidmessage_from_remote__close_device__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__close_device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define chidmessage_from_remote__close_all_devices__field_descriptors NULL
#define chidmessage_from_remote__close_all_devices__field_indices_by_name NULL
#define chidmessage_from_remote__close_all_devices__number_ranges NULL
const ProtobufCMessageDescriptor chidmessage_from_remote__close_all_devices__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote.CloseAllDevices",
  "CloseAllDevices",
  "CHIDMessageFromRemote__CloseAllDevices",
  "",
  sizeof(CHIDMessageFromRemote__CloseAllDevices),
  0,
  chidmessage_from_remote__close_all_devices__field_descriptors,
  chidmessage_from_remote__close_all_devices__field_indices_by_name,
  0,  chidmessage_from_remote__close_all_devices__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__close_all_devices__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chidmessage_from_remote__field_descriptors[5] =
{
  {
    "update_device_list",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote, command_case),
    offsetof(CHIDMessageFromRemote, update_device_list),
    &chidmessage_from_remote__update_device_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote, command_case),
    offsetof(CHIDMessageFromRemote, response),
    &chidmessage_from_remote__request_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reports",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote, command_case),
    offsetof(CHIDMessageFromRemote, reports),
    &chidmessage_from_remote__device_input_reports__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "close_device",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote, command_case),
    offsetof(CHIDMessageFromRemote, close_device),
    &chidmessage_from_remote__close_device__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "close_all_devices",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CHIDMessageFromRemote, command_case),
    offsetof(CHIDMessageFromRemote, close_all_devices),
    &chidmessage_from_remote__close_all_devices__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chidmessage_from_remote__field_indices_by_name[] = {
  4,   /* field[4] = close_all_devices */
  3,   /* field[3] = close_device */
  2,   /* field[2] = reports */
  1,   /* field[1] = response */
  0,   /* field[0] = update_device_list */
};
static const ProtobufCIntRange chidmessage_from_remote__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chidmessage_from_remote__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CHIDMessageFromRemote",
  "CHIDMessageFromRemote",
  "CHIDMessageFromRemote",
  "",
  sizeof(CHIDMessageFromRemote),
  5,
  chidmessage_from_remote__field_descriptors,
  chidmessage_from_remote__field_indices_by_name,
  1,  chidmessage_from_remote__number_ranges,
  (ProtobufCMessageInit) chidmessage_from_remote__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ehiddevice_location__enum_values_by_number[3] =
{
  { "k_EDeviceLocationLocal", "k_EDeviceLocationLocal", 0 },
  { "k_EDeviceLocationRemote", "k_EDeviceLocationRemote", 2 },
  { "k_EDeviceLocationAny", "k_EDeviceLocationAny", 3 },
};
static const ProtobufCIntRange ehiddevice_location__value_ranges[] = {
{0, 0},{2, 1},{0, 3}
};
static const ProtobufCEnumValueIndex ehiddevice_location__enum_values_by_name[3] =
{
  { "k_EDeviceLocationAny", 2 },
  { "k_EDeviceLocationLocal", 0 },
  { "k_EDeviceLocationRemote", 1 },
};
const ProtobufCEnumDescriptor ehiddevice_location__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EHIDDeviceLocation",
  "EHIDDeviceLocation",
  "EHIDDeviceLocation",
  "",
  3,
  ehiddevice_location__enum_values_by_number,
  3,
  ehiddevice_location__enum_values_by_name,
  2,
  ehiddevice_location__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ehiddevice_disconnect_method__enum_values_by_number[4] =
{
  { "k_EDeviceDisconnectMethodUnknown", "k_EDeviceDisconnectMethodUnknown", 0 },
  { "k_EDeviceDisconnectMethodBluetooth", "k_EDeviceDisconnectMethodBluetooth", 1 },
  { "k_EDeviceDisconnectMethodFeatureReport", "k_EDeviceDisconnectMethodFeatureReport", 2 },
  { "k_EDeviceDisconnectMethodOutputReport", "k_EDeviceDisconnectMethodOutputReport", 3 },
};
static const ProtobufCIntRange ehiddevice_disconnect_method__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ehiddevice_disconnect_method__enum_values_by_name[4] =
{
  { "k_EDeviceDisconnectMethodBluetooth", 1 },
  { "k_EDeviceDisconnectMethodFeatureReport", 2 },
  { "k_EDeviceDisconnectMethodOutputReport", 3 },
  { "k_EDeviceDisconnectMethodUnknown", 0 },
};
const ProtobufCEnumDescriptor ehiddevice_disconnect_method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EHIDDeviceDisconnectMethod",
  "EHIDDeviceDisconnectMethod",
  "EHIDDeviceDisconnectMethod",
  "",
  4,
  ehiddevice_disconnect_method__enum_values_by_number,
  4,
  ehiddevice_disconnect_method__enum_values_by_name,
  1,
  ehiddevice_disconnect_method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
